[meta]
firstName = "Akshay"
lastName = "Sharma"
role = "Software Developer"
about = """I’m passionate about building tools to help people save time and do more with their lives. ¯\ (ツ) /¯


I am a graduate student in College of Information and Computer Sciences at University of Massachusetts Amherst doing my Masters with a focus on Machine Learning and NLP. You can read my research articles  [here](https://scholar.google.com/citations?hl=en&user=dO6oyWQAAAAJ). I also worked as a software developer at Intuit IDC (TurboTax Desktop Team) from Aug 2017 to July 2021. I did my bachelors (B.Tech) from National Institute of Technology, Karnataka with a major in Information Technology. I am an Open Source contributor and my interests like in Machine Learning and Natural Language Processing. I like to solve real world problems with computer programming.

Most of my projects are hosted on github.

When I’m not hacking on code I will most likely be playing football, fiddling with my guitar ,reading a fiction, gaming with my friends or watching some anime.

If our interests match or you just want to say Hi! just drop an email or ping me on twitter. My social networking details are shared below."""

[[social]]
name = "github"
url = "https://github.com/akaysh"
logo = "https://img.shields.io/github/followers/akaysh?label=GitHub&style=social"

[[social]]
name = "linkedin"
url = "https://linkedin.com/in/akshay-sharma-1995"
logo = "https://img.shields.io/badge/Linkedin-grey?logo=linkedin&style=social"

[[social]]
name = "twitter"
url = "https://twitter.com/akay_sh"
logo = "https://img.shields.io/twitter/follow/akay_sh?label=Twitter&style=social"

[[projects]]
name = "NeuralPDE"
url  = "https://github.com/SciML/NeuralPDE.jl"
stars = "https://img.shields.io/github/stars/SciML/NeuralPDE.jl?style=plastic&amp;labelColor=343b41"
forks = "https://img.shields.io/github/forks/SciML/NeuralPDE.jl?style=plastic&amp;labelColor=343b41"

[[projects]]
name = "Spider Monkey Optimization"
url = "https://github.com/akaysh/SpiderMonkey.jl"
stars = "https://img.shields.io/github/stars/akaysh/SpiderMonkey.jl?style=plastic&amp;labelColor=343b41"
forks = "https://img.shields.io/github/forks/akaysh/SpiderMonkey.jl?style=plastic&amp;labelColor=343b41"

[[projects]]
name = "ML with Julia"
url = "https://github.com/akaysh/MLWithJulia"
stars = "https://img.shields.io/github/stars/akaysh/MLWithJulia?style=plastic&amp;labelColor=343b41"
forks = "https://img.shields.io/github/forks/akaysh/MLWithJulia?style=plastic&amp;labelColor=343b41"

[[projects]]
name = "Subreddit Stock Prediction"
url = "https://github.com/mfclinton/Subreddit-Stock-Prediction"
stars = "https://img.shields.io/github/stars/mfclinton/Subreddit-Stock-Prediction?style=plastic&amp;labelColor=343b41"
forks = "https://img.shields.io/github/forks/mfclinton/Subreddit-Stock-Prediction?style=plastic&amp;labelColor=343b41"

[[projects]]
name = "Image Segmentation"
url = "https://github.com/akaysh/ImageSegmentation"
stars = "https://img.shields.io/github/stars/akaysh/ImageSegmentation?style=plastic&amp;labelColor=343b41"
forks = "https://img.shields.io/github/forks/akaysh/ImageSegmentation?style=plastic&amp;labelColor=343b41"

[[projects]]
name = "Reinforcement Learning"
url = "https://github.com/akaysh/Reinforcement-Learning-Basic"
stars = "https://img.shields.io/github/stars/akaysh/Reinforcement-Learning-Basic?style=plastic&amp;labelColor=343b41"
forks = "https://img.shields.io/github/forks/akaysh/Reinforcement-Learning-Basic?style=plastic&amp;labelColor=343b41"

[technologies]
python = "https://img.shields.io/badge/Python-black?logo=python&style=plastic"
go = "https://img.shields.io/badge/Go-black?logo=go&style=plastic"
java = "https://img.shields.io/badge/Java-black?logo=java&style=plastic"
javascript = "https://img.shields.io/badge/Javascript-black?logo=javascript&style=plastic"
typescript = "https://img.shields.io/badge/Typescript-black?logo=typescript&style=plastic"
npm = "https://img.shields.io/badge/npm-black?logo=npm&style=plastic"
nodejs = "https://img.shields.io/badge/Node.js-black?logo=node.js&style=plastic"
nestjs = "https://img.shields.io/badge/Nestjs-black?logo=nestjs&style=plastic"
angular = "https://img.shields.io/badge/Angular-black?logo=angular&style=plastic"
react = "https://img.shields.io/badge/React-black?logo=react&style=plastic"
django = "https://img.shields.io/badge/Django-black?logo=django&style=plastic"
php = "https://img.shields.io/badge/PHP-black?logo=php&style=plastic"
git = "https://img.shields.io/badge/Git-black?logo=git&style=plastic"
ansible = "https://img.shields.io/badge/Ansible-black?logo=ansible&style=plastic"
docker = "https://img.shields.io/badge/Docker-black?logo=docker&style=plastic"
kubernetes = "https://img.shields.io/badge/Kubernetes-black?logo=kubernetes&style=plastic"
github-actions = "https://img.shields.io/badge/Github%20Actions-black?logo=github-actions&style=plastic"
circleci = "https://img.shields.io/badge/CircleCI-black?logo=circleci&style=plastic"
vagrant = "https://img.shields.io/badge/Vagrant-black?logo=vagrant&style=plastic"
google-cloud-platform = "https://img.shields.io/badge/GCP-black?logo=google-cloud&style=plastic"
heroku = "https://img.shields.io/badge/Heroku-black?logo=heroku&style=plastic"
amazon-aws = "https://img.shields.io/badge/AWS-black?logo=amazon-aws&style=plastic"
numpy = "https://img.shields.io/badge/NumPy-black?logo=numpy&style=plastic"
pandas = "https://img.shields.io/badge/Pandas-black?logo=pandas&style=plastic"
scikit-learn = "https://img.shields.io/badge/Scikit%20Learn-black?logo=scikit-learn&style=plastic"
tensorflow = "https://img.shields.io/badge/Tensorflow-black?logo=tensorflow&style=plastic"
jest = "https://img.shields.io/badge/Jest-black?logo=jest&style=plastic"
cypress = "https://img.shields.io/badge/Cypress-black?logo=cypress&style=plastic"
selenium = "https://img.shields.io/badge/Selenium-black?logo=selenium&style=plastic"
elastic-stack = "https://img.shields.io/badge/Elastic%20Stack-black?logo=elastic-stack&style=plastic"
eslint = "https://img.shields.io/badge/ESLint-black?logo=eslint&style=plastic"
vscode = "https://img.shields.io/badge/VSCode-black?logo=visual-studio-code&style=plastic"
chrome = "https://img.shields.io/badge/Google%20Chrome-black?logo=google-chrome&style=plastic"
brave = "https://img.shields.io/badge/Brave-black?logo=brave&style=plastic"
duck-duck-go = "https://img.shields.io/badge/DuckDuckGo-black?logo=duckduckgo&style=plastic"
sass = "https://img.shields.io/badge/Sass-black?logo=sass&style=plastic"
styled-components = "https://img.shields.io/badge/Styled%20components-black?logo=styled-components&style=plastic"
